/**
 * Generator for a GitHub Actions workflow that performs nightly Bubble.io backups.
 * Returns the YAML content as a string — no filesystem side-effects.
 */

export interface GitHubActionsOptions {
  /** Bubble data type to back up (e.g. "User", "Product") */
  dataType: string;
  /** Bubble environment: version-test or version-live */
  env: string;
  /** Cron expression (UTC) for scheduling */
  cron: string;
  /** Number of days to retain the backup artifact in GitHub */
  retentionDays: number;
  /** Output format for the backup file */
  format: 'json' | 'csv';
  /** bubble-io-cli version to install from npm. Defaults to "latest" */
  cliVersion: string;
}

/**
 * Generates the YAML content for a GitHub Actions workflow file.
 *
 * The workflow:
 *   - Runs on a nightly cron schedule (configurable)
 *   - Supports manual dispatch with `workflow_dispatch`
 *   - Installs bubble-io-cli from npm
 *   - Configures credentials from GitHub Secrets
 *   - Runs a full backup and saves it as a GitHub Actions artifact
 *   - Writes a rich job summary to the GitHub Actions UI
 *
 * Required GitHub Secrets:
 *   BUBBLE_APP_NAME   — your Bubble app name (e.g. my-app)
 *   BUBBLE_API_KEY    — your Bubble Data API key
 */
export function generateGitHubActionsWorkflow(opts: GitHubActionsOptions): string {
  const {
    dataType,
    env,
    cron,
    retentionDays,
    format,
    cliVersion,
  } = opts;

  const cliInstall = cliVersion === 'latest'
    ? 'bubble-io-cli'
    : `bubble-io-cli@${cliVersion}`;

  return `# ============================================================
# Bubble.io Nightly Backup — auto-generated by bubble-io-cli
# ============================================================
#
# Required GitHub Secrets (add under Settings → Secrets → Actions):
#   BUBBLE_APP_NAME   — your Bubble app name (e.g. my-app)
#   BUBBLE_API_KEY    — your Bubble Data API key
#
# To trigger manually: Actions tab → "Bubble Nightly Backup" → Run workflow
# ============================================================

name: Bubble Nightly Backup

on:
  schedule:
    # Runs at ${formatCronHuman(cron)} (UTC)
    - cron: '${cron}'
  workflow_dispatch:
    inputs:
      data_type:
        description: 'Bubble data type to back up'
        required: false
        default: '${dataType}'
      environment:
        description: 'Bubble environment (version-test or version-live)'
        required: false
        default: '${env}'

jobs:
  bubble-backup:
    name: Backup Bubble Data
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # ── 1. Checkout repository ──────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v4

      # ── 2. Set up Node.js ───────────────────────────────────────────────────
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ── 3. Install bubble-io-cli from npm ───────────────────────────────────
      - name: Install bubble-io-cli
        run: npm install -g ${cliInstall}

      # ── 4. Configure Bubble credentials from GitHub Secrets ─────────────────
      - name: Configure Bubble credentials
        run: |
          bubble-io-cli config \\
            --app "\${{ secrets.BUBBLE_APP_NAME }}" \\
            --key "\${{ secrets.BUBBLE_API_KEY }}"
        env:
          BUBBLE_APP_NAME: \${{ secrets.BUBBLE_APP_NAME }}
          BUBBLE_API_KEY: \${{ secrets.BUBBLE_API_KEY }}

      # ── 5. Create backup output directory ───────────────────────────────────
      - name: Create backup directory
        run: mkdir -p ./bubble-backups

      # ── 6. Run Bubble backup ─────────────────────────────────────────────────
      - name: Run Bubble backup
        id: backup
        run: |
          # Resolve data type from manual dispatch input or default
          DATA_TYPE="\${{ github.event.inputs.data_type || '${dataType}' }}"
          ENV="\${{ github.event.inputs.environment || '${env}' }}"

          echo "data_type=\${DATA_TYPE}" >> \$GITHUB_OUTPUT
          echo "environment=\${ENV}" >> \$GITHUB_OUTPUT

          # Run backup and capture JSON result
          RESULT=\$(bubble-io-cli backup \\
            --type "\${DATA_TYPE}" \\
            --env "\${ENV}" \\
            --output "./bubble-backups" \\
            --format "${format}" \\
            --json)

          echo "result=\${RESULT}" >> \$GITHUB_OUTPUT

          # Exit non-zero if backup reported failure
          SUCCESS=\$(echo "\${RESULT}" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).success.toString())")
          if [ "\${SUCCESS}" != "true" ]; then
            echo "\${RESULT}" | node -e "const r=JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')); console.error('❌ Backup failed:', r.error); process.exit(1)"
          fi

          # Extract metrics for the summary
          RECORDS=\$(echo "\${RESULT}" | node -e "process.stdout.write(String(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).records))")
          FILE=\$(echo "\${RESULT}" | node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).file)")

          echo "records=\${RECORDS}" >> \$GITHUB_OUTPUT
          echo "file=\${FILE}" >> \$GITHUB_OUTPUT

      # ── 7. Upload backup as GitHub Actions artifact ──────────────────────────
      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: bubble-backup-\${{ steps.backup.outputs.data_type }}-\${{ github.run_id }}
          path: ./bubble-backups/
          retention-days: ${retentionDays}
          if-no-files-found: error

      # ── 8. Write GitHub Actions job summary ─────────────────────────────────
      - name: Write job summary
        if: always()
        run: |
          TIMESTAMP=\$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          cat >> \$GITHUB_STEP_SUMMARY << EOF
          ## 🫧 Bubble.io Backup Report

          | Field       | Value |
          |-------------|-------|
          | **App**     | \${{ secrets.BUBBLE_APP_NAME }} |
          | **Type**    | \${{ steps.backup.outputs.data_type }} |
          | **Env**     | \${{ steps.backup.outputs.environment }} |
          | **Records** | \${{ steps.backup.outputs.records }} |
          | **Format**  | ${format} |
          | **Run at**  | \${TIMESTAMP} |
          | **Artifact**| bubble-backup-\${{ steps.backup.outputs.data_type }}-\${{ github.run_id }} |

          > Artifact will be retained for **${retentionDays} days**.
          > To download: Actions tab → this run → Artifacts section.
          EOF
`;
}

/**
 * Converts a cron expression to a human-readable description.
 * Covers the most common patterns used in scheduled backups.
 */
function formatCronHuman(cron: string): string {
  const parts = cron.trim().split(/\s+/);
  if (parts.length !== 5) return cron;

  const [minute, hour, dom, month, dow] = parts;

  if (dom === '*' && month === '*' && dow === '*') {
    if (minute === '0' && hour !== '*') {
      return `daily at ${hour.padStart(2, '0')}:00`;
    }
    if (minute !== '*' && hour !== '*') {
      return `daily at ${hour.padStart(2, '0')}:${minute.padStart(2, '0')}`;
    }
  }

  if (dow !== '*' && dom === '*') {
    const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    const dayName = days[parseInt(dow, 10)];
    if (dayName && minute !== '*' && hour !== '*') {
      return `every ${dayName} at ${hour.padStart(2, '0')}:${minute.padStart(2, '0')}`;
    }
  }

  return cron;
}
