import { BubbleDataType, BubbleField } from '../services/bubble-meta.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Mapping from Bubble primitive field types (lowercased) to their
 * TypeScript equivalents. Relationships and unknown types are handled
 * separately in `bubbleTypeToTs`.
 */
export const BUBBLE_TYPE_MAP: Record<string, string> = {
  text: 'string',
  number: 'number',
  boolean: 'boolean',
  date: 'string',
  'geographic address': 'BubbleGeographicAddress',
  file: 'string',
  image: 'string',
  option: 'string',
  'list of text': 'string[]',
  'list of number': 'number[]',
  'list of date': 'string[]',
  'list of boolean': 'boolean[]',
  'list of file': 'string[]',
  'list of image': 'string[]',
};

/**
 * Bubble built-in system types that appear as field references.
 * These are stored as Bubble ID strings in the Data API response.
 */
const BUBBLE_SYSTEM_TYPES = new Set([
  'user',
  'fileobject',
  'geographicaddress',
  'apptext',
  'option',
  'privacyoption',
]);

/**
 * The auto-generated file header comment, injected at the top of every
 * output `.d.ts` file.
 */
const FILE_HEADER_COMMENT = `/**
 * Auto-generated by bubble-io-cli v3.0.0
 * DO NOT EDIT — regenerate with: bubble-io-cli generate types
 */`;

/**
 * Helper interface emitted whenever at least one `geographic address` field
 * is found across the generated types.
 */
const GEO_ADDRESS_INTERFACE = `/** Bubble built-in geographic address type */
export interface BubbleGeographicAddress {
  address: string;
  city?: string;
  state?: string;
  zip_code?: string;
  country?: string;
  lat?: number;
  lng?: number;
}`;

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/** Options that control how the full type file is generated. */
export interface TypeGenOptions {
  /**
   * When set, only generate the interface for this type
   * (matched against `display` name, case-insensitive).
   */
  singleType?: string;
  /** Bubble app name — embedded in the file header comment. */
  appName?: string;
  /** Bubble environment — embedded in the file header comment. */
  env?: string;
}

// ---------------------------------------------------------------------------
// Core helpers
// ---------------------------------------------------------------------------

/**
 * Resolves a single Bubble field type string to its TypeScript equivalent.
 *
 * Resolution order:
 * 1. Exact match in `BUBBLE_TYPE_MAP` (primitives and list variants)
 * 2. `list of <DataType>` pattern → `string[]` (Bubble stores list-of-thing as ID strings)
 * 3. Known custom data type (present in `knownTypes`) → `string` (ID reference)
 * 4. Built-in Bubble system type (case-insensitive) → `string`
 * 5. Fallback → `unknown`
 *
 * @param fieldType  - The raw Bubble field type string (e.g. "text", "Product", "list of User").
 * @param knownTypes - Set of all known user-defined type display names.
 */
export function bubbleTypeToTs(fieldType: string, knownTypes: Set<string>): string {
  const lower = fieldType.toLowerCase().trim();

  // 1. Direct primitive / list-of-primitive match
  if (lower in BUBBLE_TYPE_MAP) {
    return BUBBLE_TYPE_MAP[lower];
  }

  // 2. list of <SomeDataType> — return string[] (Bubble stores IDs in list fields)
  if (lower.startsWith('list of ')) {
    return 'string[]';
  }

  // 3. User-defined custom data type — stored as an ID reference
  if (knownTypes.has(fieldType)) {
    return 'string';
  }

  // 4. Bubble built-in system type (case-insensitive check)
  if (BUBBLE_SYSTEM_TYPES.has(lower)) {
    return 'string';
  }

  // 5. Safe fallback
  return 'unknown';
}

/**
 * Determines whether a field's TypeScript representation is a relationship
 * (i.e. the raw type maps to `string` because it is a data type reference,
 * not because it is a primitive Bubble `text` / `file` / etc. field).
 *
 * Used to add a clarifying JSDoc comment on relationship fields.
 */
function isRelationshipField(field: BubbleField, knownTypes: Set<string>): boolean {
  const lower = field.type.toLowerCase().trim();
  if (lower in BUBBLE_TYPE_MAP) return false; // it's a known primitive
  if (lower.startsWith('list of ')) {
    // list of primitive → not a relationship
    const inner = lower.slice('list of '.length);
    if (inner in BUBBLE_TYPE_MAP) return false;
    return true; // list of DataType → relationship list
  }
  return knownTypes.has(field.type) || BUBBLE_SYSTEM_TYPES.has(lower);
}

/**
 * Safely formats a property name for use inside a TypeScript interface.
 * Names that contain characters outside `[a-zA-Z0-9_$]` or start with
 * a digit are wrapped in single quotes.
 *
 * @example
 * formatPropertyName('name')         // 'name'
 * formatPropertyName('My Field')     // "'My Field'"
 * formatPropertyName('Creation Date') // "'Creation Date'"
 */
function formatPropertyName(name: string): string {
  const isSimple = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
  return isSimple ? name : `'${name}'`;
}

// ---------------------------------------------------------------------------
// Interface generation
// ---------------------------------------------------------------------------

/**
 * Generates a single TypeScript `export interface` block for one Bubble data type.
 *
 * Every interface includes the three mandatory Bubble system fields first:
 * - `_id` — the unique record identifier
 * - `Creation Date` — ISO 8601 creation timestamp
 * - `Modified Date` — ISO 8601 last-modified timestamp
 *
 * All user-defined fields are marked as optional (`?`) because the Bubble
 * Data API may omit fields that have not been filled in.
 *
 * @param type       - The Bubble data type definition from the Meta API.
 * @param knownTypes - Set of all user-defined type display names (for relationship detection).
 */
export function generateInterface(type: BubbleDataType, knownTypes: Set<string>): string {
  const lines: string[] = [];

  lines.push(`export interface ${type.display} {`);

  // System fields — always present, always required (read-only)
  lines.push(`  /** Unique Bubble record identifier */`);
  lines.push(`  _id: string;`);
  lines.push(`  /** ISO 8601 creation timestamp */`);
  lines.push(`  'Creation Date': string;`);
  lines.push(`  /** ISO 8601 last modification timestamp */`);
  lines.push(`  'Modified Date': string;`);

  // User-defined fields
  for (const field of type.fields) {
    const tsType = bubbleTypeToTs(field.type, knownTypes);
    const propName = formatPropertyName(field.display);
    const isRelationship = isRelationshipField(field, knownTypes);

    if (isRelationship) {
      lines.push(`  /** [${field.type}] relationship → stored as Bubble ID */`);
    } else {
      lines.push(`  /** [${field.type}] */`);
    }
    lines.push(`  ${propName}?: ${tsType};`);
  }

  lines.push(`}`);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// File-level generation
// ---------------------------------------------------------------------------

/**
 * Generates the full content of a `.d.ts` / `.ts` file containing TypeScript
 * interface definitions for one or more Bubble data types.
 *
 * The output includes:
 * 1. A DO-NOT-EDIT header comment with app/env metadata (when provided)
 * 2. The `BubbleGeographicAddress` helper interface (only when geo fields exist)
 * 3. One `export interface` block per included data type
 *
 * @param types   - All data types from the Bubble Meta API.
 * @param options - Optional filters and metadata for the file header.
 */
export function generateTypeFile(types: BubbleDataType[], options: TypeGenOptions = {}): string {
  const { singleType, appName, env } = options;

  // ── Filter types ──────────────────────────────────────────────────────────
  let targetTypes = types;
  if (singleType) {
    const lower = singleType.toLowerCase();
    targetTypes = types.filter(
      (t) => t.display.toLowerCase() === lower || t.id.toLowerCase() === lower
    );
  }

  // Build the set of all known type names for relationship resolution
  const knownTypes = new Set(types.map((t) => t.display));

  // ── Check whether any geo address fields exist (drives helper interface) ──
  const needsGeoInterface = targetTypes.some((t) =>
    t.fields.some((f) => f.type.toLowerCase() === 'geographic address')
  );

  // ── Assemble file sections ────────────────────────────────────────────────
  const sections: string[] = [];

  // 1. Header comment
  let header = FILE_HEADER_COMMENT;
  if (appName || env) {
    const metaLine = [
      appName ? `App: ${appName}` : null,
      env ? `Environment: ${env}` : null,
    ]
      .filter(Boolean)
      .join(' | ');
    header = `/**\n * Auto-generated by bubble-io-cli v3.0.0\n * ${metaLine}\n * Generated: ${new Date().toISOString()}\n *\n * DO NOT EDIT — regenerate with: bubble-io-cli generate types\n */`;
  }
  sections.push(header);

  // 2. Helper interface (only if needed)
  if (needsGeoInterface) {
    sections.push(GEO_ADDRESS_INTERFACE);
  }

  // 3. One interface per target type
  for (const type of targetTypes) {
    sections.push(generateInterface(type, knownTypes));
  }

  return sections.join('\n\n') + '\n';
}
